Update README with new build dependency and improved wording.
Added kf6-kcoreaddons-devel to build dependencies. (Error
```
CMake Error at /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
  By not providing "FindKF6CoreAddons.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF6CoreAddons", but CMake did not find one.

  Could not find a package configuration file provided by "KF6CoreAddons"
  (requested version 6.23.0) with any of the following names:

    KF6CoreAddonsConfig.cmake
    kf6coreaddons-config.cmake

  Add the installation prefix of "KF6CoreAddons" to CMAKE_PREFIX_PATH or set
  "KF6CoreAddons_DIR" to a directory containing one of the above files.  If
  "KF6CoreAddons" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/KF6Package/KF6PackageConfig.cmake:53 (find_dependency)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/lib64/cmake/Plasma/PlasmaConfig.cmake:52 (find_dependency)
  CMakeLists.txt:43 (find_package)


-- Configuring incomplete, errors occurred!
error: Bad exit status from /var/tmp/rpm-tmp.aBf3bS (%build)

RPM build warnings:
    %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.aBf3bS (%build)
```
without it)
Made Instructions more clear for install, aswell for rpm-ostree usage.